# -*- coding: utf-8 -*-

{
    "name": "NY P&W - Automated Product Name and UPC",
    "version": "14.0.1.0",
    "description": """
    #2874449 - 
    Product Names to be automatically generated from Categories.
    """,
    "summary": "Product names autogenerated from Categories. UPC autoenerated based on gender sequence and current milliseconds.",
    "author": "Odoo Inc.",
    "website": "https://www.odoo.com",
    "license": "OPL-1",
    "category": "Custom Development",
    "depends": ["base", "stock"],
    "data": ["views/nypaw_apn_product_template_views_inherit.xml"],
    "demo": [],
    "auto_install": False,
    "installable": True,
    "application": False,
    "assets": {},
}
